name: Add Label to PR
on: repository_dispatch
jobs:
  remove_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)            
            // this gets the number at the end of the content URL, which should be the issue/PR number
            const pr_link = context.payload.pr_link.split('/').pop()
            const jira_id = context.payload.jira_id
            //console.log(context)
            console.log("pr_link: " + pr_link)
            console.log("jira_id: " + jira_id)