name: Add Label to PR
on: repository_dispatch
jobs:
  add_label_to_pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TRILOGY_PERSONAL_TOKEN }}
          script: |
            //console.log(context)            
            //const owner = "JoseLVelas"
            //const repo = "Tests"
            //const owner = "trilogy-group"
            //const repo = "pulse-ui"
            
            // this gets the number at the end of the content URL, which should be the issue or PR number
            const pr_link_items = context.payload.client_payload.pr_link.split('/')
            const pr_number = pr_link_items[-1]
            const repo = pr_link_items[-3]
            const owner = pr_link_items[-4]
            const jira_id = context.payload.client_payload.jira_id
            //console.log(context)
            console.log("pr_number: " + pr_number)
            console.log("repo: " + repo)
            console.log("owner: " + owner)
            console.log("jira_id: " + jira_id)
            
            //github.rest.issues.addLabels({
            //  issue_number: pr_number,
            //  owner: owner,
            //  repo: repo,
            //  labels: ["triage"]
            //})
